### ISSUE TITLE
using rule.truthy with undefined property

### ISSUE THREAD

**Issue by tstapleton** [Mermade/oas-kit#124]
### Checklist

- [x] Linting issue

### Detailed Description

I defined a lint rule to enforce that the operation description is truthy:

```yaml
- name: operation-description
  description: operation should have a description
  object: operation
  truthy: description
```

When I run this, I get an error "There is no type adaptor `forEach` for undefined". Going through the debugger, I saw that `description` is undefined at https://github.com/Mermade/oas-kit/blob/master/packages/oas-linter/index.js#L85.

I've never used should.js so I tried it out on RunKit - https://npm.runkit.com/should - using:

```js
var should = require("should/as-function")

const a = { b: 1, c: undefined };

// this passes
should(a).have.property('c');

// this throws Error: There is no type adaptor `forEach` for undefined
// should(a.c).not.be.empty();

// this throws the AssertionError, which would be caught
should(a.c).not.be.undefined()
```

Look like a bug? Can I give you a PR with `should(object[property]).not.be.undefined();` added between the two existing `should()`s? (I promise it won't take 15 days like the last one!)

Thanks!
