### ISSUE TITLE
Add notEqual rule type

### ISSUE THREAD

**Issue by pderaaij** [Mermade/oas-kit#138]
### Checklist

- [ ] Linting issue

`speccy` currently has a rule type to see if a property does not match a certain value. As mentioned in https://github.com/wework/speccy/pull/248#issuecomment-454162130 this isn't present in `oas-linter`. Would be nice to add it to the linter.

**Comment by MikeRalphson** [comment]
Yes, I've checked and this doesn't look like it can safely be covered by `notContains` or `if/then/else`.

I think it could be implemented as a `schema` rule along these lines:

```
property: myProp
schema:
  not:
    enum:
    - myValue
```

Though if we're aiming to keep peoples'  Speccy rules working as-is, then porting `notEquals` is the way to go.

**Comment by pderaaij** [comment]
It's one of the reasons why I didn't create a PR yet, wanted to fiddle around with the schema first. Will do some testing first.

As the definition for speccy is breaking already I am leaning towards accepting a not as-is approach.

**Comment by MikeRalphson** [comment]
Yep, as Speccy is < `v1.0.0` I think we can break things if need be.

**Comment by pderaaij** [comment]
This was a hard one, but got it figured out. 

The rule checks that if you have a `default` and an `example` property in the object the aren't the same. If so, it warns you that it are duplicates.

By this definition `enum` isn't an option anymore. `const` provided by `ajv` however is a solution for this challenge. Wiht some toying around this rule fulfills the requirement of the rule:

```yaml
- name: default-and-example-are-redundant
  object: "*"
  description: don't need to define an example if its exactly the same as your default
  schema:
    dependencies:
      default:
        properties:
          example:
            not:
              const:
                "$data": "1/default"
``` 
It does however requires us to enable the `$data` option of `ajv` in the validator.
