### ISSUE TITLE
Question: Should oas-resolver resolve internal $refs?

### ISSUE THREAD

**Issue by chris-branch** [Mermade/oas-kit#142]
### Resolver issue

* [x] core functionality
* [x] CLI options
* [x] Docs updated
* [x] New test cases (minimal for now)

I have a .yaml file that contains several internal `$ref` (and 0 external `$ref`).  I expected that the output from oas-resolver would replace the `$ref` elements with the content that is targeted by the `$ref`.  However, it seems to skip internal $ref and leave the original element unchanged.  Example:

Original file:
```
....
paths:
  /v1/orders/:
    post:
      ....
      responses:
        '200':
          $ref: '#/components/schemas/Order'
....
```

Output from `speccy resolve myfile.yaml`
```
....
paths:
  /v1/orders/:
    post:
      ....
      responses:
        '200':
          $ref: '#/components/schemas/Order'
....
```

The `Order` schema does exist in the same file, and is valid. Is this correct behavior?

**Comment by MikeRalphson** [comment]
Yes, `oas-resolver` is only for resolving external `$ref`s. Internal `$ref`s are valid OpenAPI objects in and of themselves, and tools should not need them resolved to be able to process an OpenAPI document.

**Comment by chris-branch** [comment]
Thanks for the clarification.  Leaving internal references as "unresolved" seems problematic for things like `oas-linter` because an equivelent schema can be defined multiple ways (with or without `$ref`). So, it may not be possible to create a linter rule that handles both situations if internal references remain unresolved even though both versions are logically identical.

For example, consider a linter rule to enforce a certain response format.  I could do something like this:

```
rules:
- name: my-example-rule
  object: 'responses'
  description: 'Response must be foo'
  schema:
    type: object
    patternProperties:
      '^200$':
        properties:
          foo:
            type: object
        required:
          - foo
```

This works if the sub-schema for foo is authored in place:
```
paths:
  /myendpoint/:
    ....
      responses:
        '200':
          foo:
            type: object
```

But not if the sub-schema is added via an inline reference:
```
paths:
  /myendpoint/:
    ....
      responses:
        '200':
          $ref: '#/components/schemas/foo'
```

My understanding is that both versions should be identical, but that's not the way `oas-linter` sees it.  I was hoping that `oas-resolver` might help solve this.
