### ISSUE TITLE
YAML output missing quotations around examples

### ISSUE THREAD

**Issue by matthewvelie** [Mermade/oas-kit#169]
When processing a swagger 2 YAML file with a property that is a string with a "date" format and an example provided, the objected is processed properly; however, when output back as an open api 3 YAML file the example object no longer has quotations around it.  This causes the wrong example value to display in the UI.  When outputting as json this is not a problem as it is a YAML specific issue to require the quotations.

### Checklist

- [X] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [X] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description
In the initial swagger 2.0 I have a property "date range", which is shown below.  In this the example dates "2017-01-01" have quotations around them as required since they are a string example.

Swagger2:
----------------
```yaml
  date_range:
    description: 'DateRange is a type of NumericRange.'
    type: object
    properties:
      from:
        description: 'The lower bound value in the DateRange.'
        type: string
        format: date
        example: "2017-01-01"
      thru:
        description: 'The upper bound value in the DateRange.'
        type: string
        format: date
        example: "2017-01-01"
```

When outputting this as a YAML open api 3 it is represented as:

Open API 3 YAML
----------------
```yaml
    date_range:
      description: DateRange is a type of NumericRange.
      type: object
      properties:
        from:
          description: The lower bound value in the DateRange.
          type: string
          format: date
          example: 2017-01-01
        thru:
          description: The upper bound value in the DateRange.
          type: string
          format: date
          example: 2017-01-01
```

This is the exact same minus the quotes around the example.  Which causes this to be represented incorrectly in the example viewer:

 "from": {},
 "thru": {}

When converting to JSON, the inherit nature of the JSON shows this correctly based on this conversion:

            "date_range": {
                "description": "DateRange is a type of NumericRange.",
                "type": "object",
                "properties": {
                    "from": {
                        "description": "The lower bound value in the DateRange.",
                        "type": "string",
                        "format": "date",
                        "example": "2017-01-01"
                    },
                    "thru": {
                        "description": "The upper bound value in the DateRange.",
                        "type": "string",
                        "format": "date",
                        "example": "2017-01-01"
                    }
                }
            },

#### Other stuff

Running version 5.2.3.  Using the command line to convert using `swagger2openapi --yaml --refSiblings preserve --outfile out.yaml in.yaml`

**Comment by MikeRalphson** [comment]
You say above

> In this the example dates "2017-01-01" have quotations around them as required since they are a string example.

I do not believe this is correct regarding the YAML specification. Quotation marks are only required if the string value would otherwise be interpreted as a `number`, a `boolean`, `null` etc, or if it contains the # comment character.

Notice how `type: object` does not have quotation marks around it even though the value of the `type` property is of type `string`.

You mention "the UI" and "the example viewer" - what project(s) are you referring to here? I suspect they are the ones which have the problem and may not be processing the unquoted YAML correctly.

**Comment by MikeRalphson** [comment]
Closing due to inactivity - but please feel free to reopen the issue if necessary.

**Comment by Amachua** [comment]
# String number conversion issue
I've a related issue while converting a file from Swagger 2.0 to OpenAPI 3.0 but its not for the date nor the date-time but on the string that enclose a number. 

To make you understand the issue, I've attached two sample files:
- _random.txt_: with the specification in Swagger 2.0;
- _random.openapi.txt_: With the specification in OpenAPI 3.0 that was generated with the command line _swagger2openapi.ps1 -targetPath .\publish .\test\random.yaml_.

In those files, you'll see the following behavior. A string that starts with a '0' and that only contains number in it will be automatically converted to a number and lose its quotes like below:

## Definition from _random.txt_
```YAML
  RandomRequest:
    type: object
    properties:
      random_phone_number:
        description: Some string number.
        type: string
        example: "0681924019"
      other_random_phone_number:
        description: Some string number.
        type: string
        example: "681924019"
    required: [random_phone_number]
```
## Converted definition in _random.openapi.txt_

```YAML
    RandomRequest:
      type: object
      properties:
        random_phone_number:
          description: Some string number.
          type: string
          example: 681924019
        other_random_phone_number:
          description: Some string number.
          type: string
          example: "681924019"
      required:
        - random_phone_number
```

This is particularly painful since the generated sample is not valid without the quote. Do you have any idea on how to solve this? :)

[random.openapi.txt](https://github.com/Mermade/oas-kit/files/3450564/random.openapi.txt)
[random.txt](https://github.com/Mermade/oas-kit/files/3450565/random.txt)
