### ISSUE TITLE
linter doesn't complain about invalid properties under required

### ISSUE THREAD

**Issue by vitaliis** [Mermade/oas-kit#176]
### Checklist

- [ ] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain
- [ ] Linting issue

### Detailed Description
Under components > schemas there is a schema defined (e.g. `ExampleSchema`):
```
ExampleSchema:
      type: object
      properties:
        field1:
          type: string
      required:
        - fieldRequired
```
This `ExampleSchema` contains an invalid "reference" `fieldRequired`, and `fieldRequired` is not defined anywhere. The reference could have been `field1` for example.
Therefore the reference is incorrect, but the linter doesn't complain.

#### Other stuff
Using a version bundled with VSCode plugin.
