### ISSUE TITLE
[Linter] Example for validation of query params but not header params

### ISSUE THREAD

**Issue by ThomasPr** [Mermade/oas-kit#195]
Please provide a rule example that shows how a query param can be validated without applying the validation to a header param.

I can easily write a rule like that:

```json
{
  "name": "query parameters with snake case",
  "object": "parameter",
  "pattern": {
    "property": "name",
    "value": "^([a-z0-9_])*$"
  }
}
```

But this rule will be applied to query and header params. If I specify a header like that, the validation will fail:

```json
"parameters" : [ {
  "name" : "EU-client-id",
  "in" : "header",
  "required" : false,
  "type" : "string"
}]
```

It would be great if you can provide an example how to validate only `"in": "query"` params.

**Comment by MikeRalphson** [comment]
The linter rules DSL is currently not flexible enough to express the condition you want.

**Comment by MikeRalphson** [comment]
I'm really sorry, I should have updated this when we changed the schema validator used by the linter, several months ago.

You can do this with a linter rule such as:

```yaml
- name: query-parameters-snake-case
  object: parameter
  description: in:query parameters must have snake_case names
  schema:
    if:
      properties:
        in:
          const: query
    then:
      properties:
        name:
          type: string
          pattern: "^([a-z0-9_])*$"
```
