### ISSUE TITLE
reference-components-regex incomplete

### ISSUE THREAD

**Issue by stevenj** [Mermade/oas-kit#222]
### Checklist

- [X] Linting issue

The linter fails if there are `~1` or `~2` tokens in a ref path, which are used as replacements for `/` if the `/` appears in the reference.

example:
```yaml
paths:
  /v1/auth/newcustomer: # Causes a new customer email to be sent
    $ref: "v1/auth/newcustomer.yml#/paths/~1auth~1newcustomer"
```

is a valid reference to:

```yaml
paths:
    /auth/newcustomer
```

in the `v1/auth/newcustomer.ym` file.

however such a construct will yield a `reference components should all match spec. regex` error from the linter.
