### ISSUE TITLE
Feature request: support for x-discriminator

### ISSUE THREAD

**Issue by RomanGotsiy** [Mermade/oas-kit#70]
`swagger2openapi` converts `x-required`, `x-nullable` and a few others vendor extensions to corresponding OpenAPI 3 features.

Would be great to also support `x-discriminator`:

```yaml
x-discriminator:
  propertyName: type
  mapping:
    visa: "#/definitions/paymentMethodVisa"
    mastercard: "#/definitions/paymentMethodMastercard"
    amex: "#/definitions/paymentMethodAmex"
```

One of the things to not forget is to map JSON pointers from `mapping` field to new locations.
