### ISSUE TITLE
Converting "collectionFormat: csv" in OAS2 to OAS3

### ISSUE THREAD

**Issue by wing328** [Mermade/oas-kit#76]
### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 2.0
- [x] Conversion: On valid OpenAPI 2.0 input, the conversion looks wrong

### Detailed Description

When converting the following endpoint in [petstore.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml#L78-L114) from OAS2 to OAS3 using the [online converter](https://mermade.org.uk/openapi-converter):
```
  /pet/findByStatus:
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      produces:
        - application/xml
        - application/json
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          type: array
          items:
            type: string
            enum:
              - available
              - pending
              - sold
            default: available
          collectionFormat: csv
```

I got the following result in OAS3:
```
  /pet/findByStatus:
    get:
      tags:
        - pet
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      parameters:
        - name: status
          in: query
          description: Status values that need to be considered for filter
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
              enum:
                - available
                - pending
                - sold
              default: available
```

`collectionFormat: csv` in OAS2 should be converted to the following in OAS3 instead:
```
          in: query
          description: Status values that need to be considered for filter
          required: true
          style: form
          explode: false
```
but in the output generated by the online converter, `explode: false` is missing.

Ref: 
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-10
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#style-values

Am I understanding OAS3 correctly in terms of how "collectionFormat: csv" (OAS2) should be defined in OAS3?
