### ISSUE TITLE
oas-valdiator "in: query" is ok, when its actually path

### ISSUE THREAD

**Issue by philsturgeon** [Mermade/oas-kit#79]
Swagger Editor reports a semantic error for parameters which are marked as query but are defined in the URI template as part of the path.

```
Semantic error at paths./v3/companies/{company_id}/seats/{uuid}
Declared path parameter "uuid" needs to be defined as a path parameter at either the path or operation level
```

### Checklist

- [x] Conversion: I have checked my source definition is valid OpenAPI 3.0
- [x] Validation: I believe my source definition is invalid OpenAPI 3.0.x but the validator does not complain

```
  '/v3/companies/{company_id}/seats/{uuid}':
    parameters:
      - name: company_id
        in: path
        description: Company UUID
        example: 6bc8bb80-1e32-0136-eb32-0242ac11530c
        schema:
          type: string
          format: UUID
        required: true
      - name: uuid
        in: query
        description: User UUID
        example: '123456'
        schema:
          type: string
          format: uuid
        required: true
```
