### ISSUE TITLE
anyOf in schemas are not resolved

### ISSUE THREAD

**Issue by philsturgeon** [Mermade/oas-kit#84]
Hey Mike, 

This issue came in over on Speccy (https://github.com/wework/speccy/issues/119) but I think it's something that will need to take care of in oas-kit. 

<hr> 

When given a Schema Object where the `type` field is within an `anyOf`, the linter reports an error.

Consider the schema:
```
components:
  schemas:
    AnyOfExample:
      type: object
      properties:
        intOrFloatProperty:
          anyOf:
            - type: number
               format: float
            - type: integer
               format: int32
      required:
        - intOrFloatProperty
```

The linter reports: 
```
expected Object {
  anyOf: Array [
    Object { type: 'number', format: 'float' },
    Object { type: 'integer', format: 'int32' }
  ],
  ... snip ...
} to have property type
```

`anyOf` is an important aspect of JSON Schema, which OAS has adopted. It's a valid part of the specification and should be supported in linters.

## Your environment

* Node Version: 8.11.3
* macOS 10.13.6
